# Generated by Django 4.0.5 on 2022-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
